name: CI/CD Pipeline

on: 
   push:
      branches: [aula-25/08]

jobs: 
    build-test-deploy:
      runs-on: ubuntu-latest

      steps:
          - name: Baixar o código do repositório
            uses: actions/checkout@v4

          - name: Configurar o Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.14.7'

          - name: Instalar as dependências
            run: python -m pip install flask pytest

          - name: Rodar testes automatizados
            run: pytest tests/

          - name: Subir o servidor em segundo planoo
            run: |
              python app.py &
              sleep 2

          - name: Verificar saúde do servidor
            run: |
              response=$(curl -s http://localhost:5000/health)
              echo "Resposta Recebida: $response"
              echo "$response" | grep -q '"status": "ok"' || (echo "Servidor não respondeu corretamente" && exit 1)  


          - name: Derrubar o servidor
            run: pkill -f app.py || true